### ISSUE TITLE
Добавление настройки конфигурации игры через интерфейс

### ISSUE THREAD

**Issue by QuirrelForU** [QuirrelForU/Arcaventure#9]
В меню выбора игры будет находиться иконка шестеренки, которая будет позволять настроить конфигурацию игры
Конфигурацию можно сбросить до стандартных настроек

**Comment by pvperesunko** [comment]
В конфигурации игры входит скорость перемещения мяча?

**Comment by QuirrelForU** [comment]
> В конфигурации игры входит скорость перемещения мяча?

Есть изменение кол-ва жизней, скорости мяча и размера платформы.
